### ISSUE TITLE
关于fast_neural_style/运行报错的问题。

### ISSUE THREAD

**Issue by Kenneth-X** [burness/neural_style_tensorflow#1]
直接运行会出现
takes exactly 0 argument (1 given)的错误，在修改main为main(argv=None)后依旧出现了

![qq 20161215220100](https://cloud.githubusercontent.com/assets/13057987/21226795/12a50ec2-c312-11e6-9d91-c541d4d89548.png)

**Comment by burness** [comment]
@Kenneth-X  谢谢反馈
是`tf.image.resize_images`的api变了，已经修改了 因为我这边环境不太方便更新到新版本tensorflow 不能试下是否能成功运行， 你那边试试看，这个问题应该没有了，不过由于api变动可能有其他api的小问题，你到时候再贴上来。

修改方式：原先的reader.py的line20 修改为：
```
new_size = [tf.to_int32(new_height), tf.to_int32(new_width)]
resized_image = tf.image.resize_images(image, new_size)
```
或者git pull 下

**Comment by Kenneth-X** [comment]
多谢指导，已经能够运行了。我的tensorflow环境是0.11, python 2.7。非常感谢！

**Comment by burness** [comment]
@Kenneth-X  不用客气 有问题随时沟通

**Comment by chuxuezhi01** [comment]
你好，我是一个本科生也是一个初学者，看到这个项目我想学习一下，就下载了该项目，按照你所说的使用已训练好的模型快速生成图像的代码，python gen_image.py --CONTENT_IMAGES path_to_images_to_transform，如图。我想问问怎么生成不了？因为是初学者也有兴趣接触这个，所以不要笑话我问题太逊哈
![2017-03-19 16-27-58](https://cloud.githubusercontent.com/assets/26518203/24079356/1cdc2486-0cc1-11e7-8cba-32021d1e20c8.png)
